// Generates config.js from .env for local testing.
// Usage: node build-config.js

const fs = require('fs');
const path = require('path');

const envPath = path.join(__dirname, '.env');
const outPath = path.join(__dirname, 'config.js');

if (!fs.existsSync(envPath)) {
  console.error('ERROR: .env file not found. Copy .env.example to .env and add GEMINI_KEY.');
  process.exit(1);
}

function readEnvValue(source, name) {
  const pattern = new RegExp(`^\\s*${name}\\s*=\\s*(.*)\\s*$`);

  for (const line of source.split(/\r?\n/)) {
    if (!line.trim() || line.trimStart().startsWith('#')) continue;
    const match = line.match(pattern);
    if (!match) continue;

    let value = match[1].trim();
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }
    return value;
  }

  return '';
}

const env = fs.readFileSync(envPath, 'utf8');
const key = readEnvValue(env, 'GEMINI_KEY');

if (!key || key === 'your_gemini_api_key_here') {
  console.error('ERROR: GEMINI_KEY is missing or still set to the placeholder value.');
  process.exit(1);
}

const output = `// Auto-generated by build-config.js. Do not edit or commit this file.\nwindow.GEMINI_KEY = ${JSON.stringify(key)};\n`;

fs.writeFileSync(outPath, output, 'utf8');
console.log('config.js generated successfully.');
